### ISSUE TITLE
RcppAnnoy fails to compile

### ISSUE THREAD

**Issue by tiffanyhuuu** [eddelbuettel/rcppannoy#51] opened 2019-10-07 12:58 UTC
Hi,

I am a novice at Rcpp and Docker/Rocker, so bear with me for a second. I am working on pushing an image of a package to the cloud platform Seven Bridges, where my colleagues and I run data analysis. In order to do this, I am using Docker and following the steps documented on the Seven Bridges website: https://docs.sevenbridges.com/docs/install-and-run-samtools-sort

I am currently trying to install Seurat. I have an R container with devtools, but the installation terminates because RcppAnnoy is not able to compile. This is the error message I get:

```> devtools::install_github("eddelbuettel/rcppannoy")
Downloading GitHub repo eddelbuettel/rcppannoy@master
Your system is ready to build packages!
✔  checking for file ‘/tmp/RtmpFYOTSd/remotes167126338/eddelbuettel-rcppannoy-faaba96/DESCRIPTION’
─  preparing ‘RcppAnnoy’:
✔  checking DESCRIPTION meta-information
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘RcppAnnoy_0.0.13.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘RcppAnnoy’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-J8poo0/r-base-3.6.1=. -fstac
k-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c annoy.cpp -o annoy.o
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:176: annoy.o] Error 1
ERROR: compilation failed for package ‘RcppAnnoy’
* removing ‘/usr/local/lib/R/site-library/RcppAnnoy’
Error: Failed to install 'RcppAnnoy' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpFYOTSd/file15e45f97b/RcppAnnoy_0.0.13.tar.gz’ had non-zero exit status
```

Thanks, and let me know what I can do!

Tiffany

**Comment by eddelbuettel** [comment] 2019-10-07 13:09
`g++: fatal error` is almost always lack-of-RAM ram issue.  This is not anything to do with RcppAnnoy -- you need to learn how to give your container more RAM, or have it build somewhere else.

(Personal pet peeve: don't do `devtools`.  We do quality control for release. Install from CRAN.)

So you could, at a minimum, take the [Rcpp run-time container I offer](https://cloud.docker.com/u/rcpp/repository/docker/rcpp/run) and just install RcppAnnoy -- as easy as one line of `install.r RcppAnnoy`.

**Comment by tiffanyhuuu** [comment] 2019-10-07 13:16
Gotcha. I just searched up how to give my container more RAM. The link you attached doesn't work for me, though.

**Comment by eddelbuettel** [comment] 2019-10-07 13:25
Sorry about the link. I always forget what they do there. Just search for `rcpp/run` and you should find it too.

**Comment by eddelbuettel** [comment] 2019-10-08 12:08
I am going to close this as it is not a bug in RcppAnnoy but solely related to the deployment on a (too small to compile) cloud instance.

**Closed** 2019-10-08 12:20 UTC
